### ISSUE TITLE
Failed to query ownership of tokens on ethereum 

### ISSUE THREAD

**Issue by ayushmishra2005** [ChainSafe/chainbridge-deploy#58]
I was trying to query to fetch ownership of tokens on Ethereum using `cb-sol-cli erc721 owner --id 0x1` while following https://chainbridge.chainsafe.io/local/#substrate-nft-erc721, but I am getting 

{
  e: Error: hex data is odd-length (argument="value", value="0x1", code=INVALID_ARGUMENT, version=bytes/5.0.11)
      at Logger.makeError (/home/test/workspace/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/logger/lib/index.js:180:21)
      at Logger.throwError (/home/test/workspace/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/logger/lib/index.js:189:20)
      at Logger.throwArgumentError (/home/test/workspace/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/logger/lib/index.js:192:21)
      at Object.hexlify (/home/test/workspace/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/bytes/lib/index.js:177:24)
      at Command.<anonymous> (/home/test/workspace/chainbridge-deploy/cb-sol-cli/cmd/erc721.js:28:65)
      at async Promise.all (index 0)
      at async run (/home/test/workspace/chainbridge-deploy/cb-sol-cli/index.js:37:9) {
    reason: 'hex data is odd-length',
    code: 'INVALID_ARGUMENT',
    argument: 'value',
    value: '0x1'
  }
}

**Comment by ansermino** [comment]
Hey @ayushmishra2005,

The error is "hex data is odd-length". You're using `0x1` which need to be `0x01`.

**Comment by ayushmishra2005** [comment]
@ansermino   After replacing `0x1` with `0x01`, I am getting another issue: 


cb-sol-cli erc721 owner --id 0x01
{
  e: Error: call revert exception (method="ownerOf(uint256)", errorSignature="Error(string)", errorArgs=["ERC721: owner query for nonexistent token"], reason="ERC721: owner query for nonexistent token", code=CALL_EXCEPTION, version=abi/5.0.13)
      at Logger.makeError (/home/test/workspace/os/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/logger/lib/index.js:180:21)
      at Logger.throwError (/home/test/workspace/os/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/logger/lib/index.js:189:20)
      at Interface.decodeFunctionResult (/home/test/workspace/os/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/abi/lib/interface.js:289:23)
      at Contract.<anonymous> (/home/test/workspace/os/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/contracts/lib/index.js:320:56)
      at step (/home/test/workspace/os/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/contracts/lib/index.js:48:23)
      at Object.next (/home/test/workspace/os/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/contracts/lib/index.js:29:53)
      at fulfilled (/home/test/workspace/os/chainbridge-deploy/cb-sol-cli/node_modules/@ethersproject/contracts/lib/index.js:20:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    reason: 'ERC721: owner query for nonexistent token',
    code: 'CALL_EXCEPTION',
    method: 'ownerOf(uint256)',
    errorSignature: 'Error(string)',
    errorArgs: [ 'ERC721: owner query for nonexistent token' ],
    address: '0xd7E33e1bbf65dC001A0Eb1552613106CD7e40C31',
    args: [ '0x01' ],
    transaction: {
      data: '0x6352211e0000000000000000000000000000000000000000000000000000000000000001',
      to: '0xd7E33e1bbf65dC001A0Eb1552613106CD7e40C31',
      from: '0xff93B45308FD417dF303D6515aB04D9e89a750Ca'
    }
  }
}

**Comment by ansermino** [comment]
@ayushmishra2005 a token with that ID does not exist. Have you minted one already?

**Comment by ayushmishra2005** [comment]
@ansermino Where should I make the change? Could you please sugest? It looks like this document is not updated. https://chainbridge.chainsafe.io/local/#substrate-nft-erc721


![image](https://user-images.githubusercontent.com/1575561/111023885-8ff58c80-8401-11eb-8740-697362c7bae7.png)

**Comment by ayushmishra2005** [comment]
Its working fine now.
