### ISSUE TITLE
unknown option '--bridge'

### ISSUE THREAD

**Issue by Chevelle102** [ChainSafe/chainbridge-deploy#95]
i'm follow this tutorial
https://chainbridge.chainsafe.io/live-evm-bridge/

When i exec this command:
cb-sol-cli --url $SRC_GATEWAY --privateKey $SRC_PK --gasPrice 10000000000 deploy --bridge --erc20Handler --relayers $SRC_ADDR --relayerThreshold 1 --chainId 0

i have this message error:
error: unknown option '--bridge'

any idea?

**Comment by NorwegianGoat** [comment]
Try to move the `deploy --bridge --erc20Handler` part after the` cb-sol-cli` invocation. I think that I solved in this way.
`cb-sol-cli deploy --bridge --erc20Handler --url $SRC_GATEWAY --privateKey $SRC_PK --gasPrice 10000000000 --relayers $SRC_ADDR --relayerThreshold 1 --chainId 0`

**Comment by Chevelle102** [comment]
so weird, now i have this message error

#cb-sol-cli deploy --bridge --erc20Handler --url $SRC_GATEWAY --privateKey $SRC_PK --gasPrice 10000000000 --relayers $SRC_ADDR --relayerThreshold 1 --chainId 0

```
{ e:
   { Error: invalid response - 0
       at exports.XMLHttpRequest.request.onreadystatechange (/home/chevelle/chainbridge-deploy/cb-sol-cli/node_modules/ethers/utils/web.js:84:29)
       at exports.XMLHttpRequest.dispatchEvent (/home/chevelle/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
       at setState (/home/chevelle/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
       at exports.XMLHttpRequest.handleError (/home/chevelle/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
       at ClientRequest.errorHandler (/home/chevelle/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
       at ClientRequest.emit (events.js:198:13)
       at Socket.socketErrorListener (_http_client.js:401:9)
       at Socket.emit (events.js:198:13)
       at emitErrorNT (internal/streams/destroy.js:91:8)
       at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
     statusCode: 0,
     responseText:
      'Error: connect ECONNREFUSED 127.0.0.1:80\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)' } }

```

**Comment by NorwegianGoat** [comment]
> ```
>       'Error: connect ECONNREFUSED 127.0.0.1:80\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)' } }
> ```

I would say this is something related to the node you are trying to connect to. Is the node effectively running on localhost at port 80?
